# Generated by Django 4.1.5 on 2023-01-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
