# Generated by Django 4.1.5 on 2023-01-17 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_alter_movie_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(db_column='rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rating_date', models.DateField(auto_now_add=True, db_column='rating_date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
